### ISSUE TITLE
Tag a 1.3 release

### ISSUE THREAD

**Issue by pnomolos** [chrisboulton/php-resque#112]
Would be great if you could tag a 1.3 release so that a versioned release with the changes since 1.2 is available on packagist.

Thanks!

**Comment by donoftime** [comment]
+1
Don't want to use code that has atrophied for 2.5 years, but would also prefer to not ride the dev tip. Composer/Satis can mark a particular changeset, but it is much better for the maintainer to tag the changeset than to choose something arbitrary.  

While it may not be a sexy new feature, the project management work is just as helpful!

**Comment by chrisboulton** [comment]
See #274
