### ISSUE TITLE
Job class not found if using namespace

### ISSUE THREAD

**Issue by eddiejaoude** [chrisboulton/php-resque#121]
When using namespaces, the job class is not found.

I have tried Resque::enqueue('default', 'My\Job', $args); but still no luck.

Any ideas? 


**Comment by rabnawazPikesSoft** [comment]
my My_queue.php in libraries folder in code ignitor and include it on autoupload.php as well and still getting the issue the

i have tried this 
Resque::enqueue('default', 'My\queue', $timeslot);
Resque::enqueue('default', 'My_queue', $timeslot);
Resque::enqueue('default', 'application\libraries\My_queue', $timeslot);
Resque::enqueue('default', 'application\\libraries\\My_queue', $timeslot);

Resque::enqueue('default', 'application/libraries/My_queue', $timeslot);

i have use all thhis while enqueing in queue but still not find my_queue job class 

please guide me thanks

**Comment by danhunsaker** [comment]
You have to either tell Composer to load the file using PSR-4 instead of PSR-0, or rename the class so it doesn't have an underscore (`_`) in it.  The second approach will probably work better.

Don't mix `\\` and `_` in your class names.

**Comment by rabnawazPikesSoft** [comment]
@danhunsaker  I HAVE renamed the class and it class name now class name is without underscore and still getting the same error no luck 
and i am using PSR-4

**Comment by danhunsaker** [comment]
You've restarted the worker(s) after renaming?  Does the class autoload correctly in other parts of your application?  Sometimes Composer needs to regenerate the `autoload.php` in order to find everything, and you have to restart all your code for the changes to be picked up - have you tried doing that?
