### ISSUE TITLE
Running multiple workers with monit

### ISSUE THREAD

**Issue by tholder** [chrisboulton/php-resque#138]
Using the monnit example, I managed to get PHP resque working fine.

Problem is, as soon as you put multiple works in the same monit script, it completely crashes out Redis.

I believe this is due to the issue discussed here: http://nongnu.13855.n7.nabble.com/Multiple-changing-PIDs-on-a-single-file-td3181.html

Is there a solution to this? I've played with php resque pool but that seems a bit forgotten and buggy.

I mention it as an issue here as there might be an obvious solution and there just needs to be a tweak to the monit script or something added to the docs.

**Comment by nbonamy** [comment]
@ipalaus Hello. Did you also modify the source code elsewhere so that every worker PID is written to the PID file? Is a PR available? Thanks!
