### ISSUE TITLE
Redis Auth

### ISSUE THREAD

**Issue by ruslan-palahin** [chrisboulton/php-resque#140]
Is it possible to use redis server with "requirepass" option?

**Comment by nolan-interactive** [comment]
Example please.

**Comment by danhunsaker** [comment]
The README and the `bin/resque` script already provide examples of setting the backend.  The only thing you'd need to add is in the first comment on this issue.

**Comment by nolan-interactive** [comment]
Thanks, Got that, the version included in our app via composer doesn't include a bin/resque file, which appears to accept Redis DNS style URLs.

Adding the call to redis()->auth('mypass') didn't work. Removing the auth password in the Redis config got everything working...

**Comment by danhunsaker** [comment]
Ah.  Yeah.  The latest tagged version is pretty old.

**Comment by clu3** [comment]
Generally, I think the idea is you shouldn't use password for redis. You can use bind 127.0.0.1 to protect from outside access (http://redis.io/topics/security)

If you really wanna use this check the REDIS_BACKEND env in vendor/chrisboulton/php-resque/bin/resque
Set it in the env to something like, 
redis://root:PASS@127.0.0.1:6379

note that "root" is redundant and not checked by redis,
