### ISSUE TITLE
Possible issue Resque/Redis interaction, jobs not beeing queued/executed

### ISSUE THREAD

**Issue by hussfelt** [chrisboulton/php-resque#149]
We have an issue where:
- We have a record of a job's status: `"resque:job:0303372f365b078473192b4b607c3f65:status"`
- Status of job above is `Resque_Job_Status::STATUS_WAITING`
- The job has never been executed (We log all job-executions to fix this issue)
- The queues are empty, queues that exist are "default" and "stage"
- We suppose that the job WAS pushed as we got a response from PhpResque when the job was added

Supposed problems:
- Job failed somehow while popping, never reaching the next staus
- Job was not added to a queue properly

Any ideas?

Currently we have 4000+ jobs that most probably was not executed, but all of them have status WAITING - and there are no way of actually finding out what they where supposed to do and "re-execute them"...(?) :)

**Comment by peterjmit** [comment]
Please see #228 which is potentially related to this issue
