### ISSUE TITLE
file:demo/queue.php  the problem is related to the var $argv[2] ?

### ISSUE THREAD

**Issue by liujingyu** [chrisboulton/php-resque#151]
I think it's right!
try 
if (empty($argv[2])) {
    $jobId = Resque:enqueue('default', $argv[1], $args, true);
} else {
    $jobId = Resque::enqueue($argv[1], $argv[2], $args, true);
}
instead of 
$jobId = Resque::enqueue($argv[1], $argv[2], $args, true);

**Comment by chrisboulton** [comment]
Fixed by #152
