### ISSUE TITLE
Adding more core members

### ISSUE THREAD

**Issue by ruudk** [chrisboulton/php-resque#153]
I think we should have more core members (with repository access) because the project has a bit stalled. The last release was over a year ago.

There are 39 open issues (with 14 PR's).

What do you think @chrisboulton @zachgarwood @danhunsaker?

For example: The maintainer of BCCResqueBundle (Symfony2 implementation of PHP Resque) didn't had much time too so he added me and 2 others and now we're making progress again.

**Comment by danhunsaker** [comment]
So.  Adding more maintainers here, or switching to a fork for that?
