### ISSUE TITLE
Job status incorrect

### ISSUE THREAD

**Issue by driesken** [chrisboulton/php-resque#219]
It seems that tracking the status of jobs doesn't seem to be working for me. I've written the following to check the status every second:
Resque::enqueue('processqueue', 'ProcessMessage', $args);
$parsehost_token = Resque::enqueue('hostqueue', 'parseHost', $args, true);
			
while(!$done){
$status = new Resque_Job_Status($parsehost_token);
var_dump($status);
switch($status->get()){
	case Resque_Job_Status::STATUS_WAITING:
	echo "WAITING\n";
	break;
	case Resque_Job_Status::STATUS_RUNNING:
	echo "RUNNING\n";
	break;
	case Resque_Job_Status::STATUS_FAILED:
	$done = true;
	break;
	case Resque_Job_Status::STATUS_COMPLETE:
	$done = true;
	break;
}
sleep(1);
}

It keeps "RUNNING" forever, even when the script in the job exits with exit(0).

var_dump gives me the following:
object(Resque_Job_Status)#18 (2) {
  ["id":"Resque_Job_Status":private]=>
  string(32) "a6289a79d5059f7e53f5a6a7e3a895d1"
  ["isTracking":"Resque_Job_Status":private]=>
  NULL
}

So 'isTracking' is set to "false", even if i have enqueued the job with the 4th parameter set to "true"?

What am I not seeing here?

**Comment by edjeavons** [comment]
I've been having this same problem and resolved it by switching to the master release. After a *lot* of stabbing in the dark I noticed how outdated the v1.2 tag was so figured it was worth trying an update.

So, in `composer.json`:

    "require": {
        "chrisboulton/php-resque": "dev-master"
    }

I see this is old issue but perhaps that will help someone else who comes across the same problem.

**Comment by fj123ll** [comment]
> I've been having this same problem and resolved it by switching to the master release. After a _lot_ of stabbing in the dark I noticed how outdated the v1.2 tag was so figured it was worth trying an update.
> 
> So, in `composer.json`:
> 
> ```
> "require": {
>     "chrisboulton/php-resque": "dev-master"
> }
> ```
> 
> I see this is old issue but perhaps that will help someone else who comes across the same problem.

这个答案真的给我感动了  爱你哟
