### ISSUE TITLE
Connecting to redis via unix sockets not possible

### ISSUE THREAD

**Issue by beheh** [chrisboulton/php-resque#222]
The version 1.2 accepted a `unix://<path>` style socket path to connect to redis. credis does still support this, but the Resque_Redis-Wrapper does not allow the "unix" protocol in [`parseDsn`](https://github.com/chrisboulton/php-resque/blob/master/lib/Resque/Redis.php#L156).

This should be allowed, although unix sockets do not understand the notion of ports.
A workaround is to use `Resque::setBackend(array(array('host' => 'unix://<path>')))`, but this is not easily possible on the command line to use the supplied bin/resque worker (this works because an array is directly passed to Credis_Cluster, which then initializes Credis_Client(s)).

I also barely found any documentation of this feature. It would be nice if this is mentioned at least somewhere.

**Comment by lenar** [comment]
@beheh: It actually works if you just pass absolute path of unix socket as hostname (without scheme etc). And yes, ```unix://``` prefix isn't supported right now at all. And as you said just adding ```unix``` to allowed schemes in ```Resque_Redis::parseDns()``` doesn't cut it because of the shortcomings of ```parse_url()``` function. Somebody should do something :).

**Comment by chrisboulton** [comment]
Addressed by #298
