### ISSUE TITLE
New Relic transaction naming support for Jobs?

### ISSUE THREAD

**Issue by epicwhale** [chrisboulton/php-resque#224]
I was looking for pointers / support on how can each Job be reported as a separate New Relic transaction.

Right now in my New Relic, I see the `bin/resque` as one thick transaction with no further clarity on which job is taking how long.. 

Would like your thoughts on better integration with New Relic?

**Comment by rrhyne** [comment]
@epicwhale very curious about where you ended up with this!

**Comment by epicwhale** [comment]
@rrhyne No where. New Relic officially confirmed that this wont work as expected as pcntl_fork is not supported by New Relic's PHP Agent. If you are a New Relic customer, you should make a feature request in their support desk too, just in case they decide to hurry this up.
