### ISSUE TITLE
Redis minimum version requirement

### ISSUE THREAD

**Issue by yonas** [chrisboulton/php-resque#230]
Hi,

Why is the minimum version requirement v2.2? Which required feature or bug fix was included in this version?

Cheers,

**Comment by danhunsaker** [comment]
Is anything below Redis 2.2 even available anymore?

**Comment by danhunsaker** [comment]
That said, my guess would be the ability to write to keys with expirations set.  There are other enhancements that make everything a hell of a lot faster, but otherwise, that's the only major change I see that would make an impact.

**Comment by yonas** [comment]
I'm using Redis server 1.3.15 on Ubuntu 10.10. php-resque seems to work fine.

How do I test if php-resque can write to keys with expirations set?

**Comment by danhunsaker** [comment]
If it isn't exploding in your face, then it should be fine.  But I'd upgrade that server ASAP.  10.10 support has been gone for a long while, and 10.04 expires in a few months.

**Comment by yonas** [comment]
Thanks, will do :)
