### ISSUE TITLE
[PROBLEM] Environement variable $PATH has not same value of systeme

### ISSUE THREAD

**Issue by onetest** [chrisboulton/php-resque#231]
Environement variable $PATH has not same value of systeme

When run code "exec('gocr')" in system shell it's works, When run same code in resque job don't work and display "gocr: command not found"

**Comment by danhunsaker** [comment]
All environment variables used by PHP-Resque come from PHP itself, which means that your workers and jobs inherit the environment variables available in the shell at the time you start the workers.  That means you need to restart the workers after you change the `PATH`, and that you need to ensure the `PATH` is correct in whatever environment you start the workers from.

**Comment by onetest** [comment]
ok thank's
