### ISSUE TITLE
Fresque type worker tool

### ISSUE THREAD

**Issue by HMAZonderland** [chrisboulton/php-resque#236]
I've just started to use php-resque and I think its a great product. But command line support or even for setting up workers as services into the OS is really poor. I've been looking into tools which would do sorta the same thing as php-resque and found https://github.com/kamisama/Fresque.

It would be cool if php-resque could be managed with Fresque or in a Fresque like manner.

**Comment by danhunsaker** [comment]
Only @kamisama can say whether Fresque (still?) works with PHP-Resque.  That said, the project was designed to be a *direct* port from the original Ruby version, and although it hasn't kept pace with it, it did replicate the current state of Resque at the time (as closely as PHP can replicate Ruby, anyway), and therefore any limitations of the CLI are inherited from there.

When momentum is restored here, I'm sure the CLI will improve along with everything else.
