### ISSUE TITLE
Enable Queue Prefixing for 1.2.*

### ISSUE THREAD

**Issue by zanderbaldwin** [chrisboulton/php-resque#244]
Whilst it seems that you have done it in the `master` branch, queue prefixing (whilst completed in the library itself) with the `PREFIX` environmental variable isn't enabled in the CLI script for version `1.2`.

I can't create a pull request for the `master` branch because that is being used for your next major (or minor) version. Could you please create a branch off the `1.2` tag so that I can create a pull request (or add it in yourself)? It can then be released as `1.2.1` while everyone waits for version 2! :smile:

Whilst I am looking forward to your next version, I unfortunately really need prefixing support due to limited Redis resources and stable-only version requirements (and I really dislike hacking vendor source files!)

**Comment by rajibahmed** [comment]
I guess you can have your own fork of this project.  And install that via composer?  (just an idea)

**Comment by zanderbaldwin** [comment]
I could (and I am for now), but that wouldn't help everyone else who would like to use the `PREFIX` environmental setting (already defined in the `resque.php` worker script but never actually used).

Having to use different queues for different projects/applications on the same Redis instance doesn't feel like clean way to go, that's all.
