### ISSUE TITLE
Anyway to queue jobs without using composer?

### ISSUE THREAD

**Issue by ptdev** [chrisboulton/php-resque#258]
The readme states that using composer isn't strictly necessary but there's no example on how exactly one can use php-resque without it.
I'm using composer for the console app and that works fine as expected, but I have another webapp where I'd like to enqueue some jobs that's not using composer.
I've tried requiring the lib/Resque.php but when calling enqueue I get a "Class 'Resque_Event' not found" error.
So my question is: is there any simpler way to queue a job without adding composer to my project just to load php-resque and call enqueue()?

**Comment by danhunsaker** [comment]
You'll want to `require()` the other class files your web app will use.  The easiest way to do that is with a PSR-0 compliant autoloader (we're not PSR-4 compliant, yet, so PSR-0 is required), which Composer provides, but others are available as well.

**Comment by ptdev** [comment]
Thanks @danhunsaker, that did the trick.
For completion purposes (in case anyone else needs or searches for this info in the future), these were the steps.
Extract the contents of the "lib" folder somewhere.
Also needed is the "Client.php" file from the credis lib (https://github.com/colinmollenhour/credis).
Then:

```
require '/someplace/Client.php';
require '/someplace/Resque.php';
require '/someplace/Resque/Event.php';
require '/someplace/Resque/Job.php';
require '/someplace/Resque/Redis.php';
```
