### ISSUE TITLE
What does the 'Psr\Log\LogLevel::INFO' mean ? 

### ISSUE THREAD

**Issue by jinleileiking** [chrisboulton/php-resque#259]
In the code 
```
    $logger->log(Psr\Log\LogLevel::INFO, 'Prefix set to {prefix}', array('prefix' => $PREFIX));
```

What does the 'Psr\Log\LogLevel::INFO' mean ?  

The composer will change the \Log\ when compile ? 

thanks.

**Comment by danhunsaker** [comment]
That's a reference to a constant defined in the PSR-3 spec, and the `LogLevel` class in the `Psr\Log` namespace.  Any PSR-3 compliant logger implementation will accept that constant as its first argument, which is the log level (in this case, the `INFO` level).

**Comment by jinleileiking** [comment]
thans, a stupid question.
