### ISSUE TITLE
Not getting the bin

### ISSUE THREAD

**Issue by justechn** [chrisboulton/php-resque#260]
Hey guys,

I know I must be doing something wrong because when I add this via composer I am not getting the bin dir and I cannot run QUEUE=file_serve php bin/resque because bin/resque does not exist. Am I missing something in composer?

**Comment by danhunsaker** [comment]
Composer installs version `1.2` by default (most recent tag), which doesn't have the `bin` dir, yet.  You'll have to use `dev-master` to get that.

Alternately, the `bin/resque` file was `resque.php` in the project root in `1.2`, so you could adjust your command accordingly.

**Comment by rajibahmed** [comment]
This bug is weird I use the latest hash number on composer.json file. Which fixes this problem.

**Comment by Anahkiasen** [comment]
Can we get a new tag? Last tag was in 2012

**Comment by chrisboulton** [comment]
See #274
