### ISSUE TITLE
Tag some versions

### ISSUE THREAD

**Issue by bmidget** [chrisboulton/php-resque#262]
The last version you tagged for this repo was Oct 13, 2012.

Please regularly tag some sort of release for your repo so those of us who install using composer don't have to use `dev-master`. It's not good practice for anyone to need to do that.

**Comment by danhunsaker** [comment]
Please search through existing issues before creating duplicates in a condescending tone.

If this project was progressing more regularly, releases would be tagged.  However, several 1.3 features are still incomplete, but enough has changed that a 1.2.x release no longer makes sense under semantic versioning.  So even though there have been commits to master in the interim, tagging any of them would be irresponsible at best.

All this is detailed in other issues about tagging releases.

**Comment by bmidget** [comment]
I understand what you're saying, but at the same time, there are tons of changes between 1.2 and master. Sure they don't constitute a 1.3 version. Maybe 1.2.5? Surely there is something changes could be tagged as so devs wouldn't have to use dev-master as our composer version. It's just asking for trouble from my standpoint when something is committed to master that breaks my entire application.

**Comment by danhunsaker** [comment]
This is the risk of using a project which is not currently being actively maintained.

**Comment by bmidget** [comment]
This has got to be the dumbest thing I've heard in my life. Three years' worth of changes. Small, but significant enough that it currently works and the last tagged version doesn't.

I'm sure every single user of this repo would agree with me that if someone took all of five minutes and tagged even a minor release (hey, why not 1.2.1), then we'll be happy knowing our locked in version won't break one day on our application.

**Comment by chrisboulton** [comment]
Hi Ben,

I absolutely agree with you.

My reality is right now, I don't have the time to sit down and make the last set of changes I believe are necessary to cut a release that I am happy to sign off on the stability of.

At Bigcommerce, we're using a revision-locked-almost-HEAD copy of php-resque at the moment, but we're using it with a custom Redis client that provides Sentinel compatibility and uses Predis as the underlying Redis library. I want to get the library change into master and in the next release, as Predis is a better library overall.

I do also want to fold php-resque-scheduler into the next release to ensure compatibility (right now there is a nasty compatibility issue which is documented over in that repository and possibly here too). php-resque-scheduler itself needs some tests.

If a tagged release is super important to you now, I hope that means you are volunteering to help me test a branch with the above proposed changes if I can put one together. Alternatively, you can do what other people have been doing and choose an appropriate gitref and lock to that.

**Comment by warren5236** [comment]
@chrisboulton I would be willing to work on testing the next release .  What do you need me to do?

**Comment by chrisboulton** [comment]
#274 is the "new" all encompassing "this project is doomed" issue - I'm going to close this one out in favour of that.
