### ISSUE TITLE
composer install/update does not include /bin directory

### ISSUE THREAD

**Issue by syedrakib** [chrisboulton/php-resque#266]
i am only getting the "demo, extras, lib, test" directories when doing composer update. I can't get the "bin" directory. What needs to be done?

**Comment by danhunsaker** [comment]
For now, you need to set your version to `dev/master`.

**Comment by syedrakib** [comment]
@danhunsaker can you please elaborate? How do i ensure composer installs dev-master?

**Comment by danhunsaker** [comment]
See #254.

**Comment by syedrakib** [comment]
thanks @danhunsaker

**Comment by RVN-BR** [comment]
+1... was a bit stumped after thinking 1.2 was "stabler" :)  back to dev-master

thanks
