### ISSUE TITLE
PHP Warning:  Error while sending QUERY packet after 1 job

### ISSUE THREAD

**Issue by azhard4int** [chrisboulton/php-resque#269]
I am getting this error, and i have been consistently looking for some solution to get this work around.

PHP Warning:  Error while sending QUERY packet. 

Even, i closed all mysql connections once the job is done, for the first time job gets done successfully.

Next time I get the above error I mentioned.

**Comment by danhunsaker** [comment]
You need to close and reopen the connection when the job starts.  Forking reuses everything from the parent process, including the MySQL connection.

**Comment by azhard4int** [comment]
@danhunsaker, thanks mate. 

We were able to resolve the issue.

**Comment by jeetkr** [comment]
@danhunsaker didnt get you, could you please elaborate more?
 I am facing the same issue. Here is my snippet:
public function perform()
    {
	    $mysql = Mysql::getInstance();
		EH::setErrorHandler();
		$user_id = $this->args['user_id'];

	    	// add karma score
	    $mysql->query("UPDATE user SET karma = karma + 1 WHERE id={$user_id}");
	   .
           .
     }
I am reopening the connection at start, still get a "error while sending query packet". Also, this isnt a packet size issue since it works fine if put in main php thread and not in resque.

**Comment by danhunsaker** [comment]
Reopening the connection needs to be done inside the `perform()` method, or if you have multiple jobs, you can add a `beforePerform` hook and reconnect there. Every job runs in a fork - a completely new process with an exact copy of the old one's memory contents (though it's copy-on-write, so it's still really fast) - so every job needs to reconnect immediately before trying to use the DB, every time.
