### ISSUE TITLE
Connect to unix socket instead of tcp?

### ISSUE THREAD

**Issue by ivankristianto** [chrisboulton/php-resque#273]
Is there a possibility to connect to unix socket instead of tcp?

**Comment by danhunsaker** [comment]
PHP-Resque uses Credis to communicate with Redis, so if Credis supports sockets, so does Resque.  Be sure to use `dev-master`, though.  There are some untagged changes to how the server address is handled that will probably be the difference between it working and not.

**Comment by chrisboulton** [comment]
See #298
