### ISSUE TITLE
Redis overload without Exception

### ISSUE THREAD

**Issue by adeptofvoltron** [chrisboulton/php-resque#283]
I just set on my redis-server config:
 maxmemory 5gb
maxmemory-policy noeviction

According to config file, I ought to get error after the memory limit is reached.

I started to run in for loop something like:
\Resque::push($queueName, $aLotOfData);

After like 300k requests, there were no new elements in queue added. Unlucku I haven't get any errors.
Any idea?

**Comment by danhunsaker** [comment]
It's a pretty safe bet that either Credis isn't handling the errors properly (we're not using the latest version, anymore), or your Resque doesn't check for errors when enqueuing jobs (I don't think my PR for that has been merged, yet...).
