### ISSUE TITLE
Is it time to point users to moved repo?

### ISSUE THREAD

**Issue by rajibahmed** [chrisboulton/php-resque#302]
@chrisboulton @danhunsaker 

Shall we add , this repo is now part to official resque organisation and need to update packagist I guess?

And shall we start a slack channel for conversation and ideas to improve the lib ?

//Best

**Comment by danhunsaker** [comment]
Chris hasn't quite finished his cleanup and migration efforts, so no, it's not quite time for that.

As to Slack, I'm game for having a place to converse out of band, even before the transition is complete.

**Comment by chrisboulton** [comment]
See #274
