### ISSUE TITLE
Composer locks due to psr/log dependency version

### ISSUE THREAD

**Issue by dinbrca** [chrisboulton/php-resque#319]
I get a composer error while trying to require `resquebundle/resque` which uses `chrisboulton/php-resque`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: psr/log[1.0.2, 1.0.0].
    - Can only install one of: psr/log[1.0.0, 1.0.2].
    - Can only install one of: psr/log[1.0.0, 1.0.2].
    - chrisboulton/php-resque dev-master requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - resquebundle/resque dev-master requires chrisboulton/php-resque dev-master -> satisfiable by chrisboulton/php-resque[dev-master].
    - Installation request for resquebundle/resque dev-master -> satisfiable by resquebundle/resque[dev-master].
    - Installation request for psr/log (locked at 1.0.2) -> satisfiable by psr/log[1.0.2].
```

This is resulted because I already have a package which uses psr/log 1.0.2 and `chrisboulton/php-resque` uses psr/log 1.0.0.. can you guys change it to "~1.0"? 

Because else - this requires me to lock my composer.json to `1.0`.

Thanks in advance,
Din.

**Comment by pprkut** [comment]
This should be solved with da25ae1, no?

**Comment by dinbrca** [comment]
Yup.. Opened both an issue and a merge request..

**Comment by danhunsaker** [comment]
If an issue is resolved, it's probably a good idea to close it. Please?

**Comment by lwtju** [comment]
if u come across error like this, u can try composer update first.
