### ISSUE TITLE
How to prefix a new job? Is it even necessary?

### ISSUE THREAD

**Issue by sn0opy** [chrisboulton/php-resque#327]
Hey,

I'm planning to have a job system in multiple apps using the same Redis DB. To make sure they don't mess with each other I'd like to use the prefix option. I set the prefix in my worker via `\Resque_Redis::prefix()`. After enqueuing some jobs, none of them will get processed.

Is there any way to prefix the jobs as well? 

It looks like they all use the `resque` default prefix.

**Comment by danhunsaker** [comment]
The same method can be used in your apps to set prefixes there, as well.  Just be sure to call it somewhere in your application's setup phase, before jobs are queued,

**Comment by sn0opy** [comment]
@danhunsaker yep, that works for me. Haven't even thought about that. Thanks!
