### ISSUE TITLE
What is missing for 1.3 release?

### ISSUE THREAD

**Issue by gabel** [chrisboulton/php-resque#339]
Any reason why there is no 1.3 release tag available?

**Comment by kareltrcalek** [comment]
Hi,
 there are plenty of reasons and ongoing discussions why it is not possible, like:

 * Maybe this project needs new maintainer? : https://github.com/chrisboulton/php-resque/issues/274
 * composer install version 1.2 old tag : https://github.com/chrisboulton/php-resque/issues/315
 * Tag some version : https://github.com/chrisboulton/php-resque/issues/262
 * begging for new stable release : https://github.com/chrisboulton/php-resque/issues/238
 * tag new release 1.3.0 : https://github.com/chrisboulton/php-resque/issues/203

and so on. This project is maybe abandoned and is definitely not reliable.
