### ISSUE TITLE
Package could't install, missing package ext-pcntl-0.0.0.0

### ISSUE THREAD

**Issue by jasverix** [chrisboulton/php-resque#340]
Hi,

May you please remove that requirement over to suggestions? The package won't install on our linux servers.

**Comment by danhunsaker** [comment]
It's a hard requirement - without pcntl, forking doesn't work, and essentially the entire project stops working properly. Please install pcntl and try again.

**Comment by jasverix** [comment]
We have pcntl installed and working - it is just composer that does not understand that.

I created a pull request #341 for this issue - newie to github, sorry.

**Comment by jasverix** [comment]
![image](https://cloud.githubusercontent.com/assets/22839684/25470154/0d343108-2b21-11e7-8e0d-5d37fe00d874.png)

Screenshot of the exception from composer.

**Comment by danhunsaker** [comment]
In that case, ensure the extension is actually enabled for the CLI SAPI, because Composer can't detect something that isn't loaded. This is a local configuration issue, not a repo issue.

**Comment by jasverix** [comment]
We also have six developers on Windows machines, running Resque locally, because we have operations requiring Resque. PHP on windows is not default compiled with pcntl, but that is no problem on local developer computers.

My only hope is that you can move it from requirements to suggestions and write something about it, like I did in #341. But if it is not possible, then I will create a fork.
