### ISSUE TITLE
Resque_Job::create() ignores return value of Resque::push

### ISSUE THREAD

**Issue by jasverix** [chrisboulton/php-resque#344]
Line 71 in Resque_Job. If Resque::push returns false, you should throw an exception or something. Now you are just going on as nothing is wrong - but the job is not stored to the queue.

json_encode() fails because we had bytes in the string, I think. That is our problem... but your problem is that Resque did nothing, and the jobs is just gone...

**Comment by jasverix** [comment]
Look at this commit in my fork of this project. I think you should do something like this.

https://github.com/jasverix/php-resque/commit/8a6b3aa040941950ea870d930aea0fe803f7eeca

**Comment by danhunsaker** [comment]
We have discussed this issue a large number of times, with several PRs addressing it.

**Comment by jasverix** [comment]
Then I would suggest you fix it. We have used our entire work day cleaning up mess after a lot of jobs just disappeared.

But in general, I am very happy with this package. Thank you for the good job! I will now close this issue.

**Comment by danhunsaker** [comment]
I'm not the project maintainer, just a user who knows the project pretty well. But setting aside the very rude response, here - I'm sorry you've spent so much time making changes that have already been suggested, but that's not a reason to lash out at volunteer devs on a project nobody pays for - a review of the time between the latest tag and the present, a look through the existing issues and pull requests, and even a look at time between the most recent commits to master, would clearly indicate this project isn't being maintained at the level you appear to expect. This is a fairly important consideration to make before deciding to use it in projects of your own. I might suggest investigating other queue engines (the Laravel project has one that works very similarly to PHP-Resque) if your project relies on active dependencies.

**Comment by jasverix** [comment]
I am sorry, had a long and quite frustrating day today.

As I said, I am in general very happy about this package. Thank you for the good job.

For our part it works good now, from my fork.
