### ISSUE TITLE
Hey, are you guys planning on releasing any updates to 1.2?

### ISSUE THREAD

**Issue by jardayn** [chrisboulton/php-resque#351]
Seems like a lot was added since 2012 (when 1.2 was released).

Are there any plans in releasing a 1.2.1 with updated code?

**Comment by danhunsaker** [comment]
Is it not allowed by the TOS to search through existing issues or something? This is a duplicate of so many others I'm not even gonna tag them here.

Yes, there will be new tags.

No, it won't happen any time soon.

Use `dev-master` as your version constraint until it does.

And please forgive my exasperated snark.

**Comment by jardayn** [comment]
@danhunsaker no prob Dan. I actually came in to delete this issue, because I've found this https://github.com/chrisboulton/php-resque/issues/274 

No problem with the snark.
