### ISSUE TITLE
Cannot works

### ISSUE THREAD

**Issue by razonyang** [chrisboulton/php-resque#352]
when i started resque got the following message and no daemon is created
```
../chrisboulton/php-resque/bin/resque
```

**Comment by danhunsaker** [comment]
@razonyang Can you tell us more about your setup and how you're using it? What OS are you using? How was PHP-Resque installed? Are you using the latest tag, or `master`? How are you starting Resque? Basically, we need enough info to reproduce your setup and issue.

**Comment by razonyang** [comment]
@danhunsaker 
- Installation: Composer
- Resque version: master
- OS: Linux(Centos distribution)
- Setup: `VERBOSE=1 QUEUE=* php /path-to-app/vendor/bin/resque`, but got above message, no daemon. PS: this command works on my laptop(LinuxMint distribution).

When I changed `/path-to-app/vendor/bin/resque` to ` /path-to-app/vendor/chrisboulton/php-resque/bin/resque`, it works fine, but I don't know why.

Additional, the server's vendor directory are from local(my laptop), and the executable file `/path-to-app/vendor/bin/resque` is existence.

**Comment by danhunsaker** [comment]
So `vendor/bin/resque` is supposed to be a symlink to `vendor/chrisboulton/php-resque/bin/resque` - can you confirm that's the case on your CentOS system? Everything else looks correct except that.

**Comment by razonyang** [comment]
@danhunsaker Sorry about this issue, I checked the content of `/vendor/bin/resque` on server,
got `../chrisboulton/php-resque/bin/resque`(seems like a symlink to the real executable file) :(

I do not know why it's content like that(I have replaced it via FizeZilla).

Thank you for your kind reply :)
