### ISSUE TITLE
QUEUE=mail: Command not found.

### ISSUE THREAD

**Issue by Aexus** [chrisboulton/php-resque#361]
The running environment is FreeBSD, and the pcntl extension has been installed. What's the wrong thing? Can tell me how to deal with it, thank you.

**Comment by danhunsaker** [comment]
Your shell isn't treating `QUEUE=mail` as an environment variable assignment. Either switch to Bash, or check your shell's help system for the correct way to set evars, and set them separately before starting the worker process.

**Comment by Aexus** [comment]
Thanks
