### ISSUE TITLE
Please archive this repository -> This package is abandoned and no longer maintained. The author suggests using the resque/php-resque package instead.

### ISSUE THREAD

**Issue by ruudk** [chrisboulton/php-resque#371]
I found out that chrisboulton/php-resque is finally marked as abandoned.

Can you please change the description to:
```
This package is abandoned and no longer maintained. The author suggests using the resque/php-resque package instead.

```

and then mark this project as archived.

It will help others.

**Comment by ruudk** [comment]
@chrisboulton

**Comment by ruudk** [comment]
The new repository by @zomble is as dead as this one.

**Comment by danhunsaker** [comment]
I'm assuming that's not the one at resque/php-resque?

**Comment by ruudk** [comment]
You're right, I was looking at a wrong fork, this is the good one https://github.com/resque/php-resque

**Comment by danhunsaker** [comment]
Yeah, that's the one I'm maintaining, so I was confused. :slightly_smiling_face:

**Comment by ruudk** [comment]
Now I get my confusion, when I run `composer install` it says this:
```
Package chrisboulton/php-resque is abandoned, you should avoid using it. Use resque/php-resque instead.
```

When I go googled for that package I found https://packagist.org/packages/php-resque/resque, but that's actually the wrong one. I added a Issue to warn everybody to not use that package. https://github.com/php-resque/resque/issues/20

**Comment by ruudk** [comment]
@chrisboulton one more try... before I give up.
