### ISSUE TITLE
The documentation for 'scan' is described

### ISSUE THREAD

**Issue by phpxianyu** [chrisboulton/php-resque#380]
$count = 100;
$pattern = 'worker:processing:*';
Resque::redis()->scan($cursor, 'match', $pattern, 'count', $count);
return value is false,
please have specific documentation

**Comment by phpxianyu** [comment]
@danhunsaker help

**Comment by danhunsaker** [comment]
I'm not sure Credis properly supports `scan`. At the very least, PHP Resque doesn't do anything special with it.

**Comment by phpxianyu** [comment]
Thank you for your reply. Does PHP Resque support this parameter  `scan`?

**Comment by phpxianyu** [comment]
Is there a document about PHP Resque 'scan' for this parameter ?

**Comment by danhunsaker** [comment]
If Credis doesn't support it, neither does PHP Resque.

**Comment by phpxianyu** [comment]
thank you，I know what to do
