### ISSUE TITLE
fwrite infinite loop on broken pipe

### ISSUE THREAD

**Issue by khughitt** [chrisboulton/php-resque#50]
In an application I have where tasks may take up to 5-6 minutes the workers end up going in infinite loops with an error message to the effect of:

> PHP Notice:  fwrite(): send of 898 bytes failed with errno=32 Broken pipe in /var/www/lib/Redisent/Redisent.php on line 74

It looks like the same issue was reported upstream and a pull request submitted (https://github.com/jdp/redisent/issues/10).

**Comment by 3nr1c** [comment]
Hi, I know this should be fixed from a long time now, but I'm getting the exact same notice. I had to change my composer.json version to "dev-master".

Please consider tagging a new version with the most recent code, as using the dev-master can be a bit insecure if somebody wants to use this in production.

**Comment by danhunsaker** [comment]
At this point, your best bet might be to use my fork instead...  Registered on Packagist under danhunsaker/php-resque.
