### ISSUE TITLE
PHP Warnings after jobs

### ISSUE THREAD

**Issue by scragg0x** [chrisboulton/php-resque#74]
PHP Warning:  Error while sending STMT_CLOSE packet. PID=31710 in Unknown on line 0

Warning: Error while sending STMT_CLOSE packet. PID=31710 in Unknown on line 0
PHP Warning:  Unknown: Error occured while closing statement in Unknown on line 0

I get the above warnings after every processed job.  I'm not sure what is causing them.  They don't seem to be causing any problems.  Anyone have an idea of what it could be?

**Comment by rlweb** [comment]
This could be due to forking for example a pdo connection. I'm having the same issue. I'm using the eloquent package from laravel but outside of laravel. 

The issue seems to be the connection is dropped so laravel automatically reconnects. I've tried setting the connection to null on the setup of the job but that didn't help. I'll post my example later when I'm nearer a computer

**Comment by azhard4int** [comment]
@rlweb , hey bro, can you post that example?

I am having the similar issue:

PHP Warning:  Error while sending QUERY packet. PID=6060 in

**Comment by rlweb** [comment]
Sounds like the query is either taking too long, is it mysql or redis which is returning this?

**Comment by zjsxwc** [comment]
I have the same problem today when my doctrine orm is querying entities in a job.

my workaround is to reconnect the database at the setUp method of job:

```
    public function setUp() {
        global $kernel;
        if (method_exists($kernel,'getContainer')) {
            $this->container = $kernel->getContainer();
        }

        $doctrine = $this->container->get("doctrine");
        /** @var \Doctrine\DBAL\Connection $connection */
        $connection = $doctrine->getConnection();
        $connection->close();
        $connection->connect();

    }

    public function perform() {

    }

    public function tearDown() {
        $doctrine = $this->container->get("doctrine");
        /** @var \Doctrine\DBAL\Connection $connection */
        $connection = $doctrine->getConnection();
        $connection->close();
    }

```

**Comment by danhunsaker** [comment]
Note: Reconnecting to databases after a fork is not a workaround, IT IS REQUIRED. You have to acquire a new handle to the DB, because the old one belongs to the parent process. And PHP won't reconnect for you.
